version: "3.3"
services:
  # Redis configuration file example
  # https://raw.githubusercontent.com/antirez/redis/4.0/redis.conf
  master:
    image: redis:4.0.8-alpine
    network_mode: "host"
    volumes:
      - type: volume
        source: master-data
        target: /data
    command: [
      '--requirepass "${REDIS_PWD}"',
      '--masterauth "${REDIS_PWD}"',
      '--maxmemory 512mb',
      '--maxmemory-policy volatile-ttl',
      '--save ""',
    ]


  node-1: &node
    image: redis:4.0.8-alpine
    network_mode: "host"
    depends_on:
      - master
    volumes:
      - type: volume
        source: node-1-data
        target: /data
      - type: volume
        source: node-1-data
        target: /tmp
    command: [
      '--port 6380',
      '--requirepass "${REDIS_PWD}"',
      '--slaveof "${MASTER_IP}" "${MASTER_PORT}"',
      '--masterauth "${REDIS_PWD}"',
      '--save ""',
    ]

  node-2: 
    <<: *node
    volumes:
      - type: volume
        source: node-2-data
        target: /data
      - type: volume
        source: node-2-data
        target: /tmp
    command: [
      '--port 6381',
      '--requirepass "${REDIS_PWD}"',
      '--slaveof "${MASTER_IP}" "${MASTER_PORT}"',
      '--masterauth "${REDIS_PWD}"',
      '--save ""',
    ]

  sentinel-1: &sentinel
    build:
      context: ./sentinel
      dockerfile: Dockerfile-sentinel
    image: redis-sentinel:dev
    network_mode: "host"
    environment:
      - SENTINEL_REDIS_PWD=${REDIS_PWD}
      - SENTINEL_MASTER_NAME=${MASTER_IP}
      - SENTINEL_REDIS_PORT=${MASTER_PORT}
      - SENTINEL_QUORUM=2
      - SENTINEL_PORT=${SENTINEL_PORT_1}
      - SENTINEL_DOWN_AFTER=3000
    command: [
      '${SENTINEL_CONF_PATH}',
      '--sentinel'
    ]
    depends_on:
      - master
      - node-1
      - node-2

  sentinel-2:
    <<: *sentinel
    environment:
      - SENTINEL_PORT=${SENTINEL_PORT_2}
      - SENTINEL_REDIS_PWD=${REDIS_PWD}
      - SENTINEL_MASTER_NAME=${MASTER_IP}
      - SENTINEL_REDIS_PORT=${MASTER_PORT}
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=3000
    
  sentinel-3:
    <<: *sentinel
    environment:
      - SENTINEL_PORT=${SENTINEL_PORT_3}
      - SENTINEL_REDIS_PWD=${REDIS_PWD}
      - SENTINEL_MASTER_NAME=${MASTER_IP}
      - SENTINEL_REDIS_PORT=${MASTER_PORT}
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=3000

  nginx:
    image: nginx:1.13.9-alpine
    network_mode: "host"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    extra_hosts:
       SENTINEL_IP: ${SENTINEL_IP}
    depends_on:
      - sentinel-1
      - sentinel-2
      - sentinel-3


volumes:
  master-data:
  node-1-data:
  node-2-data:

